config/routes.rb
Bookstore::Application.routes.draw do
  resources :books, only: :index do
    collection do
      post :import
      get :autocomplete
    end
  end

  root to: 'books#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books

  def to_s
    name
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :subjects

  searchkick autocomplete: ['title']

  def self.import(olid)
    client = Openlibrary::Client.new
    book_data = client.book(olid)
    book = Book.new
    book.title = book_data.title
    book.number_of_pages = book_data.number_of_pages
    book.coverimage = "http://covers.openlibrary.org/b/id/#{book_data.covers.first}-M.jpg"
    book.publish_date = book_data.publish_date
    book.save!
    book_data.authors.each do |author_data|
      author_olid = author_data[:key].split("/").last
      author_name = client.author(author_olid).name
      book.authors << Author.find_or_create_by!(name: author_name)
    end
    book_data.subjects.each do |subject|
      book.subjects << Subject.find_or_create_by!(name: subject)
    end
    book
  rescue => e
    raise ImportError
  end

  class ImportError < StandardError; end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      @books = Book.search(params[:query], page: params[:page])
    else
      @books = Book.all.page params[:page]
    end
  end

  def autocomplete
    render json: Book.search(params[:query], autocomplete: true, limit: 10).map(&:title)
  end

  def import
    book = Book.import params[:olid]
    notice = "Imported #{book.title}"
    redirect_to books_path, notice: notice
  rescue Book::ImportError
    redirect_to books_path, alert: "Failed to import book"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_for(*paths)
    "active" if paths.any? do |path|
      controller, action = path.split("/")
      controller == controller_name && (action.blank? || action == action_name)
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.slim
.media
  .pull-left.book-cover
    = image_tag book.coverimage, class: "media-object", width: "100px"
  .media-body
    h4.media-heading = book.title
    .authors = book.authors.join(", ")
    .publish_date = book.publish_date
    = "#{book.number_of_pages} pages"

app/views/books/index.html.slim
= form_tag books_path, class: "form-inline", method: :get do
  .input-group.input-group-lg
    - if params[:query].present?
      .input-group-btn
        = link_to "clear", books_path, class: "btn btn-default"
    = text_field_tag :query, params[:query], class: "form-control", id: "book_search", autocomplete: "off"
    .input-group-btn
      = submit_tag "Search", class: "btn btn-primary"

= render @books

= paginate @books

hr

= form_tag import_books_path, class: "form-inline" do
  .form-group
    = text_field_tag :olid, "", placeholder: "OLID", class: "form-control"
  '
  = submit_tag "Import book", class: "btn btn-default"
  '  Import books from the
  = link_to "Open Library", "https://openlibrary.org/"

app/views/books/show.html.slim
h1 Books#show
p Find me in app/views/books/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bookstore
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js"
    = csrf_meta_tags

body
  nav.navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        button.navbar-toggle data-toggle="collapse" data-target=".main-navbar-collapse"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to "Bookstore", root_path, class: "navbar-brand"
      .collapse.navbar-collapse.main-navbar-collapse
        ul.nav.navbar-nav
          li class=active_for("books")
            = link_to "Books", books_path

  .container
    - flash.each do |type, message|
      .alert.fade.in class=bootstrap_class_for(type)
        button.close data-dismiss="alert" aria-hidden="true" &times;
        = message

    = yield